version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: highpal-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - highpal-network

  # Optional: Kibana for Elasticsearch management UI
  kibana:
    image: kibana:8.11.0
    container_name: highpal-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - highpal-network

volumes:
  elasticsearch_data:
    driver: local

networks:
  highpal-network:
    driver: bridge
